apiVersion: v1
kind: Service
metadata:
    labels:
        app: kafka-app
    name: kafka-service
spec:
    ports:
        - name: kafka-port1
          port: 9092
          protocol: TCP
          targetPort: 9092
        - name: kafka-port2
          port: 9093
          protocol: TCP
          targetPort: 9093
    selector:
        app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: kafka-app
    name: kafka

spec:
    serviceName: kafka-service
    replicas: 1
    selector:
        matchLabels:
            app: kafka-app
    template:
        metadata:
            labels:
                app: kafka-app
        spec:
            containers:
               - image: docker.io/confluentinc/confluent-local:latest
                 imagePullPolicy: IfNotPresent
                 name: kafka
                 ports:
                     - containerPort: 29092
                     - containerPort: 9092
                     - containerPort: 9093

                 env:
                      - name: ORDINAL_NUMBER
                        valueFrom:
                           fieldRef:
                               fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
                      - name: KAFKA_NODE_ID
                        value: "$(ORDINAL_NUMBER)"
                      - name: CLUSTER_ID
                        value: "ODhCODhFMjEyNDZCNEI0ME"
                      - name: POD_NAME
                        valueFrom:
                         fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                      - name: KAFKA_LISTENERS
                        value: "CONTROLLER://:29092,PLAINTEXT://:9092, PLAINTEXT_HOST://:9093"
                      - name: KAFKA_CONTROLLER_QUORUM_VOTERS
#                        value: "0@kafka-0.kafka-service.default.svc.cluster.local:29092,1@kafka-1.kafka-service.default.svc.cluster.local:29092,2@kafka-2.kafka-service.default.svc.cluster.local:29092"
#                        value: "0@kafka-0.kafka-service.default.svc.cluster.local:29092,1@kafka-1.kafka-service.default.svc.cluster.local:29092"
                        value: "0@kafka-0.kafka-service.default.svc.cluster.local:29092"
                      - name: KAFKA_ADVERTISED_LISTENERS
                        value: "PLAINTEXT://localhost:9092, PLAINTEXT_HOST://kafka-service:9093"
                      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                        value: "1"
#                      - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
#                        value: "1"
#                      - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
#                        value: "1"

#                 command:
#                      - bash
#                      - -c
#    kubectl exec -it kafka-0 -- bash
#                      - kafka-topics --create --topic greetings --replication-factor 3 --partitions 10 --bootstrap-server kafka-0:9092
