apiVersion: v2
name: postgres-chart
description: A Helm chart for PostgreSQL with CloudNativePG (CNPG) operator
type: application
version: 0.1.0
appVersion: "16"
keywords:
  - postgresql
  - database
  - cnpg
  - cloudnativepg
home: https://cloudnative-pg.io/
sources:
  - https://github.com/cloudnative-pg/cloudnative-pg
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies: []
annotations:
  category: Database

