apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-greeting
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    size: 1Gi
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    # Change the following to `ClusterImageCatalog` if needed
    kind: ImageCatalog
    name: postgresql
    major: 16
  bootstrap:
    initdb:
      database: greeting_rust
      owner: greeting_rust
      secret:
        name: postgres-greeting-secret
#      postInitSQL:
#        - "GRANT CONNECT ON DATABASE greeting_rust TO greeting_rust;"

---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: cnpg-system
spec:
  images:
    - major: 16
      image: docker.io/arnecdn/greeting-postgres:0.16
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-greeting-config
  namespace: cnpg-system
  labels:
    app: postgres-greeting
data:
#  POSTGRES_DB: "greeting_rust"
#  POSTGRES_USER: "greeting_rust"
#  POSTGRES_HOST: "cluster-example-rw"
  postgresql.conf: |
    shared_preload_libraries = 'pg_tracing'

    compute_query_id = on
    pg_tracing.max_span = 10000
    pg_tracing.track = all

    # Send spans every 2 seconds to an otel collector
    pg_tracing.otel_endpoint = http://grafana-alloy:4318/v1/traces
    pg_tracing.otel_naptime = 2000

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: postgres-greeting-secret
#  namespace: cnpg-system
#  labels:
#    app: postgres-greeting
#type: Opaque
#data:
#  POSTGRES_PASSWORD: "Z3JlZXRpbmdfcnVzdA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-greeting-secret
  namespace: cnpg-system
data:
  username: Z3JlZXRpbmdfcnVzdA==
  password: Z3JlZXRpbmdfcnVzdA==
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-greeting-service
  namespace: cnpg-system
spec:
  selector:
    cnpg.io/cluster: cluster-example
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
