apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
stringData:
  ACCESS_KEY_ID: "okjqUfVX3BQDUhz90IXn"
  ACCESS_SECRET_KEY: "E9CjwD66BK9XBqnSzYgSBUbjxbKjED89ueoiw4P7"
