{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-greeting-minio
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.backup.minioCredentials.accessKey | b64enc }}
  SECRET_ACCESS_KEY: {{ .Values.backup.minioCredentials.secretKey | b64enc }}
{{- end }}
